Issue #503 Add auto sizing side navigation pane
WildGums/Orc.Wizard pull request #504
Opened 2022-07-17 21:14 UTC by johncbaur

Issue #503 Add auto sizing side navigation pane

### Description of Change ###
I added a flag to IWizard to turn on auto size logic for the side navigation pane.  If the size of the window can accommodate the default spacing will be used.  If the size of the window is too small to use the default sizing the logic kicks in to calculate the size of the line and the spacing of the ellipses.   I tried to avoid changing the XAML design. 

### Issues Resolved ### 
fixes #503

### API Changes ###
Modified IWizard with a new flag AutoSizeSideNavigationPane.  The flag is defaulted to false to keep legacy behavior.

### Platforms Affected ### 
Test on WPF.

### Behavioral Changes ###
None, Care was taken to make this change 100% backwards compatible.  If the feature is enabled it allows for side navigation pane to auto size the space between the wizard page ellipses.

### Testing Procedure ###

Updating the ExampleSideNavigationWizard.cs constructor will exercise the new logic:
            MinSize = new System.Windows.Size(800, 600);
            MaxSize = new System.Windows.Size(1000, 600);
            AutoSizeSideNavigationPane = true;

### PR Checklist ###

- [Yes] I have included examples or tests
- [No ] I have updated the change log
- [No] I am listed in the CONTRIBUTORS file
- [Yes] Rebased on top of the target branch at time of PR
- [ ?] Changes adhere to coding standard

2022-07-17 21:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/WildGums/Orc.Wizard?pullRequest=504) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/WildGums/Orc.Wizard?pullRequest=504) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/WildGums/Orc.Wizard?pullRequest=504) it.</sub>

2022-07-18 16:34 UTC, GeertvanHorrik requested changes
Thanks for the PR. The changes look great.

A few comments:

1. Please move the old values to constants as well so they are not spread throughout the code
2. Please add this flag to the example application so we can easily test this

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml
> +                       Canvas.Top="{Binding Path= NavigationItemLineTop}"
Space here is not required, but will not break either

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            typeof(SideNavigationBreadcrumbItem), new PropertyMetadata(0));
Should default to 35 to maintain backwards compatibility?

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            typeof(SideNavigationBreadcrumbItem), new PropertyMetadata(new Thickness()));
Should default to 0 0 0 56 ?

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            if (gridMargin > 56)
Let's move default / backwards compatibility values to constants as well

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            const int ParentMarginTop = 12;
move to constant near other values

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            if (NavigationItemLineLength > 48)
move to constant near other values

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +                SetCurrentValue(NavigationItemLineTopProperty, 35);
move to constant near other values

2022-07-18 16:34 UTC, GeertvanHorrik commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +                SetCurrentValue(NavigationItemLineTopProperty, 35);
move to constant near other values

2022-07-20 01:47 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml
> +                       Canvas.Top="{Binding Path= NavigationItemLineTop}"
Removed space.

2022-07-20 01:47 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            typeof(SideNavigationBreadcrumbItem), new PropertyMetadata(0));
Updated default.

2022-07-20 01:48 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            typeof(SideNavigationBreadcrumbItem), new PropertyMetadata(new Thickness()));
Yes, updated default.

2022-07-20 01:49 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            if (gridMargin > 56)
Defined constants for the default values.  Using the constants in the logic now and to initialize the properties.

2022-07-20 01:49 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            const int ParentMarginTop = 12;
Colocated the constant to live with the other constants.

2022-07-20 01:51 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +            if (NavigationItemLineLength > 48)
I am hoping you mean to use the constant here.  I replaced the 48 with a constant reference.

2022-07-20 01:51 UTC, johncbaur commented on src/Orc.Wizard/Controls/SideNavigationBreadcrumbItem.xaml.cs
> +                SetCurrentValue(NavigationItemLineTopProperty, 35);
I am hoping you mean to use the constants here.  I replaced the 48 and 35 with a constant references.

2022-07-20 09:47 UTC, merged